baseURL = 'https://guhcampos.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Gustavo Campos'

# Use theme from local directory
themesDir = "themes"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 0

[module]
  [[module.imports]]
    path = "blowfish"
    disable = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Blog"
    pageRef = "blog"
    weight = 10
  [[menu.main]]
    name = "Topics"
    pageRef = "topics"
    weight = 20
  [[menu.main]]
    name = "Lists"
    pageRef = "lists"
    weight = 30
  [[menu.main]]
    name = "Resources"
    pageRef = "resources"
    weight = 40
  [[menu.main]]
    name = "Tags"
    pageRef = "tags"
    weight = 50

[params]
  description = "Personal website and blog"
  mainSections = ["blog"]

  [params.header]
    layout = "basic"    # options: basic, fixed
    showTitle = true
    showMenu = true

  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = "page"  # options: page, profile, hero, card, background, custom
    showRecent = true
    showRecentItems = 5
    showMoreLink = true
    showMoreLinkDest = "/blog"

  [params.article]
    showDate = true
    showDateUpdated = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false
    showHeadingAnchors = true
    showPagination = true
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showWordCount = true
    showComments = false

  [params.list]
    showBreadcrumbs = true
    showSummary = true
    showTableOfContents = true
    showTaxonomies = true
    groupByYear = true

  [params.sitemap]
    excludedKinds = ["taxonomy", "term"]

  [params.search]
    enable = true
    type = "fuse"

  [params.colorScheme]
    default = "dark"
    toggle = true
