baseURL = 'https://guhcampos.github.io/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Gustavo Campos'
# sectionPagesMenu = "main"

themesDir = "themes"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 0

[module]
  [[module.imports]]
    path = "blowfish"
    disable = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  topic = "topics"


[outputs]
  home = ["HTML", "RSS", "JSON"]
