[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
 name = "Música"
 weight = 20

[[main]]
name = "Playlists"
parent = "Música"
pageRef = "playlists"
weight = 20

# [[main]]
#  name = "Recursos"
#  pageRef = "recursos"
#  weight = 20

[[main]]
name = "Sobre"
pageRef = "about"
weight = 50

# ----------------

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Tópicos"
pageRef = "topics"
weight = 20
