[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
 name = "Música"
 weight = 20

[[main]]
name = "Playlists"
parent = "Música"
pageRef = "playlists"
weight = 20

# ----------------

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

# [[footer]]
# name = "Tópicos"
# pageRef = "topics"
# weight = 20
