[hugoVersion]
  extended = false
  min = "0.148.0"

[[module.imports]]
  path = "blowfish"
  disable = false

[[module.mounts]]
source = 'static/playlists'
target = 'data/playlists'
includeFiles = ['*.json']

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

[[module.mounts]]
source = 'content/pt'
target = 'content'
lang = 'pt'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'pt'


[[module.mounts]]
  source = "build/obsidian/en/posts"
  target = "content/en/posts"
  includeFiles = ['*.md']

[[module.mounts]]
  source = "build/obsidian/pt/posts]"
  target = "content/pt/posts"
  includeFiles = ['*.md']
