name: build guhcampos.github.io

on:
  push:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.1
      OBSIDIAN_VAULT: ${{ github.workspace }}/obsidian-vault
      HUGO_CONTENT: ${{ github.workspace }}/content
    steps:
      - name: checkout website repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: checkout obsidian vault
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.OBSIDIAN_VAULT }}
          ssh-key: ${{ secrets.OBSIDIAN_DEPLOY_KEY }}
          path: build/obsidian-vault
          fetch-depth: 1

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: install python
        run: uv python install

      - name: install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1'
          extended: true

      - name: install python dependencies
        run: uv sync --locked --all-extras --dev

      - name: build website
        run: uv run build

      - name: setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
